# Generated by Django 3.1.7 on 2021-03-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('result_100m', models.CharField(max_length=200)),
                ('result_long_jump', models.CharField(max_length=200)),
                ('result_shot_put', models.CharField(max_length=200)),
                ('result_high_jump', models.CharField(max_length=200)),
                ('result_400m', models.CharField(max_length=200)),
                ('result_110h', models.CharField(max_length=200)),
                ('result_discus', models.CharField(max_length=200)),
                ('result_pole_vault', models.CharField(max_length=200)),
                ('result_javelin', models.CharField(max_length=200)),
                ('result_1500m', models.CharField(max_length=200)),
                ('points_overall', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
            ],
        ),
    ]
