# Generated by Django 3.1.7 on 2021-03-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decathlon', '0002_auto_20210309_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='place',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='points_overall',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='result_110h',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='result_1500m',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='result_400m',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='result_discus',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='result_high_jump',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='result_javelin',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='result_long_jump',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='result_pole_vault',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='result_shot_put',
            field=models.FloatField(max_length=200),
        ),
    ]
