# Generated by Django 3.1.7 on 2021-03-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decathlon', '0003_auto_20210309_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='place',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='points_overall',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
