# Generated by Django 3.1.7 on 2021-03-10 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decathlon', '0004_auto_20210309_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='place',
        ),
    ]
